from classes.model import ProbabilisticAllStates


probabilisticModel = ProbabilisticAllStates()
probabilisticModel.simulate(n=10)
probabilisticModel.plot_map_of_avg_qaly_loss_by_county_4()

probabilisticModel.plot_qaly_loss_by_state_and_by_outcome()
probabilisticModel.print_overall_outcomes_and_qaly_loss()
probabilisticModel.print_qaly_loss_prorated()
probabilisticModel.plot_weekly_qaly_loss_by_outcome_vax()
probabilisticModel.plot_weekly_qaly_loss_by_outcome()
probabilisticModel.plot_map_of_avg_qaly_loss_by_county_4()
probabilisticModel.plot_weekly_deaths_sensitivity_analysis()

